### ISSUE TITLE
App crashes when invalid insert

### ISSUE THREAD

**Issue by usersxm** [chrisckchang/mean-contactlist#2]
I've just cloned this project and did nothing but establishing my mongodb_uri and then I wanted to try it locally. It works perfectly but when I make an insert (from the webpage) without any value for first and last name the server crashes and the insertion to mlab is made (empty fields). How do I prevent this?

This is the error I get: 

```
ERROR: Invalid user input
/Users/nanop/Desktop/mean-contactlist/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });
                                  ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (/Users/nanop/Desktop/mean-contactlist/node_modules/express/lib/response.js:719:10)
    at ServerResponse.send (/Users/nanop/Desktop/mean-contactlist/node_modules/express/lib/response.js:164:12)
    at ServerResponse.json (/Users/nanop/Desktop/mean-contactlist/node_modules/express/lib/response.js:250:15)
    at /Users/nanop/Desktop/mean-contactlist/server.js:72:23
    at /Users/nanop/Desktop/mean-contactlist/node_modules/mongodb/lib/collection.js:421:18
    at handleCallback (/Users/nanop/Desktop/mean-contactlist/node_modules/mongodb/lib/utils.js:96:12)
    at /Users/nanop/Desktop/mean-contactlist/node_modules/mongodb/lib/collection.js:726:5
    at /Users/nanop/Desktop/mean-contactlist/node_modules/mongodb-core/lib/connection/pool.js:428:18
    at nextTickCallbackWith0Args (node.js:433:9)
```

**Comment by chrisckchang** [comment]
If you're trying to run it locally, you'll likely have to change this line to use your local MongoDB URI: https://github.com/chrisckchang/mean-contactlist/blob/master/server.js#L17
